name: Build Container

on:
  push:
    branches:
    - main
    paths:
    - "Dockerfile"
    - "entrypoint.sh"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: rom-tools-test
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Container-Structure-Test
        run: |
          wget https://github.com/GoogleContainerTools/container-structure-test/releases/download/v1.16.0/container-structure-test-linux-amd64 \
            -O container-structure-test && chmod +x container-structure-test
          ./container-structure-test test --image rom-tools-test --config unit-test.yaml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v4

    - name: Login to ghcr.io
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u soup-bowl --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/soup-bowl/rom-tools:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
